name: Run pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: ${{ matrix.python-version }}
          # tango-controls is required for Python 2
          channels: conda-forge,tango-controls
          channel-priority: true
          activate-environment: dsconfig
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba install pytango
          python -m pip install -r requirements.txt
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest -v --cov=dsconfig
